try:
    print("dalam try")
    raise Exception
except:
    pass

print("lewat")
